CGTS:30640: Missing geo co ordinates
Wind-River/cloud-platform-deployment-manager pull request #138
Opened 2022-11-09 17:28 UTC by MahalakshmiManthiram

2022-11-09 17:36 UTC, yjian118 requested changes
Need to update the commit message or pull request message including the aim of this commit, and the tests passed

2022-11-14 18:21 UTC, MahalakshmiManthiram commented on api/v1/constructors.go
> +	log.Info("Latitude : ", spec.Latitude)
Removed info level logs.

2022-11-15 14:12 UTC, yjian118 approved these changes

2022-11-16 11:34 UTC, MahalakshmiManthiram commented
> Please remove "CGTS:30640" from the commit message. About the Test Plan, the deployment config was generated with latitude/longitude parameters using your deploy tool?

Removed ticket number from commit message. Yes, deployment config was generated with geo location coordinates using deploy tool

2022-11-16 15:00 UTC, merged