DM update automation post patching
Wind-River/cloud-platform-deployment-manager pull request #229
Opened 2023-06-26 13:13 UTC by sselvara1

This script is a utility to update DM automatically post patching. This involves:
1. pull image from configured source
2. push image to local registry
3. run anisible playbook to refresh DM

Jira: CGTS-47365

2023-06-26 13:16 UTC, yjian118 commented on scripts/dm_update_post_patch.sh
> +export MY_MIRROR=admin-2.cumulus.wrs.com:30093
Note: not all the users using this registry

2023-06-26 13:17 UTC, yjian118 commented on scripts/dm_update_post_patch.sh
> +export MY_IMAGE_TAG=WRCP_22.12-wrs.5
It doesn’t make sense to use version tag in the master branch

2023-06-26 13:18 UTC, yjian118 commented on scripts/dm_update_post_patch.sh
> +sudo crictl pull --creds "admin:Li69nux*" ${REGISTRY_LOCAL}/${MY_LOCAL_IMAGE}:${MY_IMAGE_TAG}
Credentials are not always the same

2023-06-26 13:24 UTC, yjian118 requested changes
I would suggest to abandon this commit in the DM repo. 
1 The update of the DM should use the playbook
2 Didn’t we want to leverage the sysinv to pull the new image?
3 The versions, credentials should come from the system rather than hard coded

2023-06-27 13:33 UTC, sselvara1 commented
> I would suggest to abandon this commit in the DM repo. 1 The update of the DM should use the playbook 2 Didn’t we want to leverage the sysinv to pull the new image? 3 The versions, credentials should come from the system rather than hard coded

I would suggest to abandon this commit in the DM repo.
[Susendra] I will move this commit to utility repo in starlingx project.
1 The update of the DM should use the playbook
[Susendra] sure, will replace 'helm upgrade' with 'ansible playbook'
2 Didn’t we want to leverage the sysinv to pull the new image?
[Susendra] yes, workflow diagram in HLD is updated. Will update the script to leverage sysinv to pull the new image.
3 The versions, credentials should come from the system rather than hard coded
[Susendra] ok, will get back on this.

2023-06-28 11:44 UTC, sselvara1 commented
Commit is moved to utility repo in starlingx project
https://review.opendev.org/c/starlingx/utilities/+/887154

2023-06-28 11:44 UTC, closed without merging