Ignore OpenLDAP certificate in system resource
Wind-River/cloud-platform-deployment-manager pull request #256
Opened 2023-08-22 09:20 UTC by vineela-pachchipulusu

The OpenLDAP certificate is installed during the initial unlock, so it cannot be collected after the bootstrap. This is causeing the system resource to be insync=false after unlock.

This commit intends to ignore this certificate in the DM, so DM will not take action on it.

Test Plan:
PASS: Build an image with these changes. Install it on a system. Verify that after the initial unlock the type: openldap certificate is not present on the current spec.
PASS: Generate the deployment-config.yaml using deploytool. Verify that the openldap certificate is not included on the file.

2023-08-22 14:47 UTC, yjian118 requested changes
Can you please give me the info about the purpose of this cherry-pick? I believe this commit should be cherry-picked by the author for the DM day2 operation in a proper order

2023-08-23 10:47 UTC, sselvara1 commented
pls use cherry-pick -x to capture the commit-id

2023-08-23 11:24 UTC, vineela-pachchipulusu commented
> Can you please give me the info about the purpose of this cherry-pick? I believe this commit should be cherry-picked by the author for the DM day2 operation in a proper order

The deployment of AIO-SX kept on failing when trying to deploy using the Declarative method (i.e. with deployment-config.yaml file). 'openldap' is observed to be an invalid parameter.

Here was the suggestion and hence the cherry-pick.
"The openldap cert is introduced recently, I think we may need to filter it out from the result generated by deployctl."

2023-08-23 15:12 UTC, enzocandotti approved these changes

2023-08-23 15:13 UTC, merged