Addition of platformNetwork resources to the deployment config file generated by deployctl
Wind-River/cloud-platform-deployment-manager pull request #306
Opened 2023-12-18 11:46 UTC by vineela-pachchipulusu

Addition of platformNetwork resources to the deployment config file generated by deployctl

**Test Plan:**
-PASS: **make** command of /cloud-platform-deployment-manager code is successful
-PASS: Able to generate the deployment config yaml file using deployctl

**JIRA:** CGTS-54880

2023-12-18 13:35 UTC, yjian118 commented on build/build.go
> +	always_generate_networks := []string{"storage", "mgmt"}
How about the oam and admin networks?

2023-12-18 13:39 UTC, yjian118 requested changes
Some comment about the commit message:
1. title too long
2. need a text to explain the problem and the way to address the problem
3. need to remove JIRA as that is internal, you can create an issue to address if you want
4. the text plan doesn't cover the problem to address
5. need to test both initial and reconfiguration(day2)
6. as that is a change of deployctl, require a test to apply the configuration generated

2024-01-08 15:50 UTC, vineela-pachchipulusu commented
> Some comment about the commit message:
> 
> 1. title too long
> 2. need a text to explain the problem and the way to address the problem
> 3. need to remove JIRA as that is internal, you can create an issue to address if you want
> 4. the text plan doesn't cover the problem to address
> 5. need to test both initial and reconfiguration(day2)
> 6. as that is a change of deployctl, require a test to apply the configuration generated

Hi Yuxing, for point no 5, to test for day-2 below was the error observed

![Screenshot 2024-01-04 175102](https://github.com/Wind-River/cloud-platform-deployment-manager/assets/141028344/23d6bf5a-2a31-483b-9da5-c70fd3325cf8)

2024-01-08 15:53 UTC, yjian118 commented
It indicates the 'Kind' is missing in secrets, can you compare it with the secrets in your previous deployment-config.yaml?

2024-01-08 15:55 UTC, vineela-pachchipulusu commented on build/build.go
> +	always_generate_networks := []string{"storage", "mgmt"}
oam and admin networks are also added.

2024-01-09 12:38 UTC, sselvara1 commented
> Enable deployctl to generate PlatformNetwork CRD in deployment config file
> 
> The PlatformNetwork resources that are present in the System are not getting added to the deployment config file that is generated by the deployctl tool. The function buildPlatformNetworks from the file build/build.go has the network types array which contains only type storage as of now .So the array is populated with all the required network types.
> 
> Test Plan:
> 
> 1. PASS: To generate the deployment config yaml file where PlatformNetwork
>    resources are also shown  using deployctl tool
> 2. PASS: To use the generated deployment config file to the bring up the system
>    and check if PlatformNetwork resources are applied.
> 3. PASS:  To test  initial configuration(day1)
> 4. PASS: To test reconfiguration(day2)

Below phrasing and formatting will be preferred - 

Enable deployctl to generate PlatformNetwork CRD in deployment config file

The PlatformNetwork resources that are present in the System are not getting 
added to the deployment config file that is generated by the deployctl tool.
The function buildPlatformNetworks has the network type array which contains 
only "storage" type as of now. The array is populated with the required network
types including  "mgmt", "oam", "admin".

Test Plan:

1. PASS: Generate deployment config file using deployctl wherein PlatformNetwork
             resources are captured.
2. PASS: Use the generated deployment config file to bring up the system and 
             check if PlatformNetwork resources are applied.
3. PASS: Test initial configuration (day1)
4. PASS: Test reconfiguration (day2)

2024-01-09 12:40 UTC, sselvara1 commented
Code LGTM.

2024-01-18 13:45 UTC, hugonicodemos approved these changes

2024-01-19 11:16 UTC, sselvara1 approved these changes
LGTM
PASS: Test reconfiguration (day2) - this test case can be added here - 
https://github.com/Wind-River/cloud-platform-deployment-manager/pull/315

2024-01-22 14:36 UTC, merged