Report error for 'deploy resume' when issue is unresolved
Wind-River/cloud-platform-deployment-manager pull request #390
Opened 2024-08-14 14:10 UTC by sselvara1

Below blocks are skipped when reconfig_flag is true: 
1) Search administrativeState into host resource
2) Wait until unlock task triggered

Thereby, playbook doesn't attempt to apply the config during 'deploy resume' and henceforth any unresolved errors persist but it reports deploy status as 'complete' which is incorrect.

Test Cases: (TBD)
1. PASS: Run subcloud add with deploy-config. Make sure there is an error condition that will cause DM playbook to fail. Run deploy resume, it should report error.
2. PASS: Run subcloud add with deploy-config. Make sure there is no error condition and DM playbook shall pass. Run deploy resume, it should skip above mentioned tasks.

2024-08-14 15:00 UTC, yjian118 requested changes
It breaks the day-2 operation as the tasks are not designed for day-2 operation. A day2 operation is expected in the test plan

2024-08-16 11:00 UTC, yjian118 commented
Still expect day-2 operation test with:
1 controller-0 locked
2 controller-o unlocked

2024-08-23 11:16 UTC, sselvara1 commented
> It breaks the day-2 operation as the tasks are not designed for day-2 operation. A day2 operation is expected in the test plan

Day-2 operation is added in the test plan.

2024-08-23 11:16 UTC, sselvara1 commented
> Still expect day-2 operation test with: 1 controller-0 locked 2 controller-o unlocked

Day-2 operation is tested with 
1. controller-0 locked for host resource
2. controller-0 unlocked for system resource.

2024-08-23 17:06 UTC, yjian118 requested changes
The invprovision statuses include:

UPGRADING = 'upgrading'
PROVISIONED = 'provisioned'
PROVISIONING = 'provisioning'
UNPROVISIONED = 'unprovisioned'

The following logic to wait for the finish of the initial deployment should not apply to UPGRADING and PROVISIONING.

2024-09-09 10:50 UTC, sselvara1 commented
> The invprovision statuses include:
> 
> UPGRADING = 'upgrading' PROVISIONED = 'provisioned' PROVISIONING = 'provisioning' UNPROVISIONED = 'unprovisioned'
> 
> The following logic to wait for the finish of the initial deployment should not apply to UPGRADING and PROVISIONING.

host.invprovision status set to 'provisioned' shall be used for finish of the initial deployment (day-1).
This will not be applied for 'provisioning', 'upgrading'

2024-09-09 13:10 UTC, yjian118 commented
We are not forbidding the users to run this playbook when "provisioning" or "upgrading".  The following block of error collection is to check operations like "unlocking" etc. should not apply to both case and will fail, therefore, there are two options:

1. Skip the blocks of error collection if "provisioning" or "upgrading" if you want to use this playbook in both case
2. Failed right after this check we don't want to support "provisioning" or "upgrading"

2024-09-12 11:32 UTC, sselvara1 commented on docs/playbooks/wind-river-cloud-platform-deployment-manager.yaml
> +        msg: "Skip applying the config when host is in upgrading state"
updated name and msg.

2024-09-13 12:56 UTC, yjian118 approved these changes

2024-09-13 13:47 UTC, hugonicodemos approved these changes

2024-09-13 13:47 UTC, merged