Include all status of hosts except online
Wind-River/cloud-platform-deployment-manager pull request #433
Opened 2024-12-03 12:58 UTC by sharbhar

Currently, the DM only checks for the offline state, not the power-off state, when hosts are not in simplex mode.
This change ensures that all host statuses, except online, are included.

Test-Plan
PASS: Deploy AIO-DX on VDM
PASS: DM adding the controller-1, check the controller-1 is added into the "system host-list",
power off the controller-1 using "system host-power-off controller-1

2024-12-04 14:10 UTC, yjian118 commented on docs/playbooks/wind-river-cloud-platform-deployment-manager.yaml
> +            - name: Get hosts not online if not simplex
Not online or not available

2024-12-04 14:15 UTC, yjian118 requested changes
Suggest to test: 
1. Deploy a DX successfully - must
2. After the DM adding the controller-1, check the controller-1 is added into the "system host-list", power off the controller-1 using "system host-power-off controller-1" - tricky to test

2024-12-05 18:41 UTC, sharbhar commented
> Suggest to test:
> 
> 1. Deploy a DX successfully - must
> 2. After the DM adding the controller-1, check the controller-1 is added into the "system host-list", power off the controller-1 using "system host-power-off controller-1" - tricky to test

 1st Deploy a DX successfully - must Done.
 2nd Test facing difficulty in testing

2024-12-05 19:35 UTC, yjian118 requested changes
Need to check the host status not "online" and not "available", then wait or exhaust timeout

2024-12-06 11:22 UTC, sharbhar commented
> Need to check the host status not "online" and not "available", then wait or exhaust timeout

Done

2024-12-06 13:04 UTC, hugonicodemos approved these changes

2024-12-06 13:51 UTC, wasnio approved these changes

2024-12-06 13:53 UTC, enzocandotti approved these changes

2024-12-06 13:53 UTC, merged