Add new example yaml files
Wind-River/cloud-platform-deployment-manager pull request #66
Opened 2021-03-01 11:56 UTC by gaolitao

Add new example yaml files for single nic feature and rate limiting configuraiton.

    - aio-sx-single-nic.yaml
    - aio-sx-vf-rate-limiting.yaml

2021-03-02 14:28 UTC, donpenney requested changes
Please look at the infrastructure in place for building example models. These are not just copies of a system's config model. There is a README file that explains the build.

The Makefile builds the example files, which can then be added to a commit:
https://github.com/Wind-River/cloud-platform-deployment-manager/blob/master/Makefile#L140-L151

2021-03-03 14:23 UTC, donpenney approved these changes
LGTM. Thanks!

2021-03-03 14:31 UTC, mwang3-wrs approved these changes

2021-03-03 15:28 UTC, steven-webster reviewed
LGTM, thanks Litao!

2021-03-03 15:32 UTC, merged